version: '3'

services:
  blog_api:
    build: ./deployment/
    container_name: blog_api
    ports:
      - "3300:3300"
      - "9230:9230"
    command: sh -c "/bin/bash"
    volumes:
      - ./:/var/www/html/
      - ./var/bash_history.log:/root/.bash_history
      - ./var:/var/log/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      static-network:
        ipv4_address: 172.20.128.3
    tty: true

  nginx:
    image: tutum/nginx
    container_name: nginx
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/sites-enabled/blog_api.conf
      - ./deployment/nginx.conf:/etc/nginx/sites-available/blog_api.conf
      - ./var/log:/var/log/nginx
      - ./:/var/www/html/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      static-network:
        ipv4_address: 172.20.128.1

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blog-api
    ports:
      - "5433:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      static-network:
        ipv4_address: 172.20.128.32

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      static-network:
        ipv4_address: 172.20.128.43

  kibana:
      depends_on:
        - elasticsearch
      image: docker.elastic.co/kibana/kibana:8.6.2
      container_name: kibana
      volumes:
        - kibana-data:/usr/share/kibana/data
      ports:
        - "7601:5601"
      restart: always
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      networks:
        static-network:
          ipv4_address: 172.20.128.42

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
      driver: local

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.28.0.0/24
